# This is a basic workflow to help you get started with Actions

name: CI

env:
  IMAGE_NAME: doquer


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Cache packages
        uses: actions/cache@v3
        with:
            path: |
              /var/lib/docker/
            key: docker

      - name: Build with docker
        run: docker build -t "$IMAGE_NAME" .github/workflows

      - run: docker images


      - name: Run docker
        run: |
          docker run \
            --mount type=bind,src=${GITHUB_WORKSPACE},dst=/root/ \
            "$IMAGE_NAME"



      - name: done
        run: echo "done"
